package com.group7.backend.entity;

public enum NotificationType {
    MATCH_FOUND,
    REQUEST_RECEIVED,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED,
    TASK_ASSIGNED,
    TASK_SUBMITTED,
    TASK_REVIEWED,
    NEW_MESSAGE,
    MEETING_REMINDER,
    MEETING_PENDING_CONFIRMATION,
    MEETING_CONFIRMED,
    MEETING_DECLINED,
    MEETING_AUTO_DECLINED,
    MEETING_RESCHEDULE_REQUESTED,
    MEETING_RESCHEDULE_APPROVED,
    MEETING_RESCHEDULE_REJECTED,
    MEETING_CANCELLED
}